### ISSUE TITLE
About the MSR RTE dataset used

### ISSUE THREAD

**Issue by Punchwes** [m-yoshinaka/sapphire#1]
Hi, thanks very much for sharing your alignment project, it is very interesting.

May I ask where do you obtain the MSR RTE 2006 dataset? I checked the original paper and the link it pointed to seem somewhere nonsense and invalid. Wonder would it be possible for you to give some valid links where I can download the dataset? It would be better if you could release your processed version of the dataset? (read from the paper that you have merge tokens into phrases).

**Comment by m-yoshinaka** [comment]
Hello @Punchwes,

I used the dataset downloaded from https://github.com/xuchen/jacana/tree/master/alignment-data/msr/converted instead of the original MSR RTE 2006 dataset link. These files are the dataset used in [Yao et al. (2013)](https://aclanthology.org/D13-1056/) and are **different** from those used in [Ouyang and McKeown (2019)](https://aclanthology.org/P19-1467/) and our paper.

The preprocess by Ouyang and McKeown (2019) (and our paper) is simple:
1. exclude sentence pairs with no *possible* alignment,
2. merge simply consecutive alignments, e.g. ['cute', 'cute'] and ['dog', 'dogs'] → ['cute dog', 'cute dogs'].

(On evaluation, they decomposed phrase alignments to word alignments, like ['cute dog', 'cute dogs'] → ['cute', 'cute'], ['cute', 'dogs'], ['dog', 'cute'], and ['dog', 'dogs']. See their paper for the reason for this process.)

I will possibly share the preprocess scripts and/or processed data later if needed and possible.

**Comment by Punchwes** [comment]
Thanks very much! That is very helpful!!
